version: '3'
services:
  server:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    container_name: flask
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    env_file: docker/database.conf
    expose:
      - 8080
    # ports:
    #   - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: docker/database.conf
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
