"""Initial migration

Revision ID: 3f2bfde440d6
Revises: 
Create Date: 2020-12-26 15:50:44.296832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2bfde440d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pagina', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('pagina'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('tipo_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.Enum('kg', 'gr', 'ltr', 'ml', name='unidades'), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('tipo_insumo_id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proceso_id'], ['proceso.id'], ),
    sa.ForeignKeyConstraint(['tipo_insumo_id'], ['tipo_insumo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('insumo_proveedor',
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('insumo_id', 'proveedor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insumo_proveedor')
    op.drop_table('insumo')
    op.drop_table('tipo_insumo')
    op.drop_table('proveedor')
    op.drop_table('proceso')
    # ### end Alembic commands ###
