"""Association table

Revision ID: 79b1ed93edc9
Revises: 0cc0e70fee26
Create Date: 2020-12-24 22:15:21.198866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b1ed93edc9'
down_revision = '0cc0e70fee26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo_proveedor',
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('insumo_id', 'proveedor_id')
    )
    op.drop_table('proveedor_insumo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_insumo',
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insumo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], name='proveedor_insumo_insumo_id_fkey'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name='proveedor_insumo_proveedor_id_fkey'),
    sa.PrimaryKeyConstraint('proveedor_id', 'insumo_id', name='proveedor_insumo_pkey')
    )
    op.drop_table('insumo_proveedor')
    # ### end Alembic commands ###
