"""Fix Association table

Revision ID: de92d13595a3
Revises: 79b1ed93edc9
Create Date: 2020-12-24 22:33:00.762266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de92d13595a3'
down_revision = '79b1ed93edc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'insumo_proveedor', 'insumo', ['insumo_id'], ['id'])
    op.create_foreign_key(None, 'insumo_proveedor', 'proveedor', ['proveedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insumo_proveedor', type_='foreignkey')
    op.drop_constraint(None, 'insumo_proveedor', type_='foreignkey')
    # ### end Alembic commands ###
