"""Atributos nullable

Revision ID: e6c332e4fc61
Revises: 3f2bfde440d6
Create Date: 2021-01-09 13:28:39.012062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6c332e4fc61'
down_revision = '3f2bfde440d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insumo', 'unidad',
               existing_type=postgresql.ENUM('kg', 'gr', 'ltr', 'ml', name='unidades'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insumo', 'unidad',
               existing_type=postgresql.ENUM('kg', 'gr', 'ltr', 'ml', name='unidades'),
               nullable=True)
    # ### end Alembic commands ###
